.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Added github templates for feature and bug requests
#182
=> #182 added github issue templates

.circleci/config.yml, cmd/flags/http.go, pkg/app/app.go, pkg/ethereum/caller_eth.go, tests/e2e/auth_test.go, tests/e2e/certificates, tests/e2e/healthz_test.go, tests/e2e/keys_test.go
=> fixes for e2e in circle ci

pkg/common/runnable.go, pkg/http/server/healthz.go, pkg/http/server/healthz_test.go, src/auth/manager/service.go, src/infra/postgres/client/client.go, src/infra/postgres/postgres.go, src/manifests/manager/manager_local.go, src/nodes/manager/service.go, src/stores/database/database.go, src/stores/database/mock/database.go, src/stores/database/postgres/database.go, src/stores/manager/service.go
- Added PG check on ready
- #285
=> #285 validate PG conn in readiness

src/aliases/api/handlers/handlers.go, src/infra/http/types.go, src/stores/api/handlers/ethereum.go, src/stores/api/handlers/keys.go, src/stores/api/handlers/secrets.go, src/stores/api/handlers/types.go, src/stores/api/types/keys.go
=> some swagger docs fixes

.env.sample, Dockerfile, cmd/flags/http.go, docker-compose.yml, pkg/ethereum/args.go, src/infra/hashicorp/client/parsers.go, src/nodes/interceptor/eea_send_transaction.go, src/nodes/interceptor/eea_send_transaction_test.go, src/stores/api/formatters/eth1.go, src/stores/api/types/ethereum.go, src/stores/connectors/ethereum/sign.go, src/stores/connectors/ethereum/sign_test.go, tests/acceptance/store_test_ethereum.go
- rename https flags for better consistency
- prevent panic on empty hashicorp error list
- added migrations to docker image for prod envs
- added support for gas, gasPrice and value within EEA tx (https://besu.hyperledger.org/en/stable/Concepts/Privacy/Private-Transactions/)
- fix issue on eea request formatter
-
=> http flags | panic on hashicorp err | migrations | EEA failure

CHANGELOG.md, README.md, docker-compose.latest.yml
=> update how to run QKM

.env.sample, cmd/flags/auth.go, cmd/util.go, docker-compose.yml
Add password decoding for CA certs in generate jwt tool
=> Add password decoding for CA certs

docker-compose.dev.yml, docker-compose.yml
=> adding docker compose auth variable to commons

src/stores/api/types/ethereum.go, src/stores/api/types/keys.go, src/stores/database/postgres/database.go, src/stores/entities/annotations.go, src/stores/manager/service.go
=> Fix swagger

.env.dev.sample, .env.sample, Dockerfile, Makefile, README.md, cmd/flags/http.go, docker-compose.dev.yml, docker-compose.yml, go.mod, go.sum, src/infra/hashicorp/client/config.go, src/infra/hashicorp/client/parsers.go
=> Bad image repository name

deps/hashicorp/docker-compose.yml, pkg/crypto/eddsa.go, pkg/json/validate.go, src/stores/api/types/keys.go, src/stores/connectors/keys/keys.go, src/stores/connectors/utils/keys_verify.go, src/stores/entities/algo.go, src/stores/store/keys/local/local.go, src/stores/store/keys/local/local_test.go, tests/acceptance/store_test_keys.go, tests/acceptance/utils/hashicorp.go, tests/e2e/keys_test.go
rename bn254 to babyjubjub + use new plugin v1.0.0
=> rename bn254 to babyjubjub

CHANGELOG.md, README.md
=> doc(changelog): update changelog and readme to prepare v21.9.0

tests/e2e/alias_test.go, tests/e2e/json_rpc_test.go
fix the e2e currently failing after the merge of #413
=> Alias value kinds fix e2e

CHANGELOG.md, src/infra/hashicorp/token/file-watcher.go
=> File watcher cherry pick

CHANGELOG.md
=> Update CHANGELOG.md v21.9.3

src/nodes/interceptor/eea_send_transaction.go, src/nodes/interceptor/eea_send_transaction_test.go, src/nodes/interceptor/eth_accounts_test.go, src/nodes/interceptor/eth_sign_test.go, src/nodes/interceptor/eth_sign_transaction_test.go, src/nodes/interceptor/interceptor.go, src/nodes/interceptor/interceptor_test.go, src/nodes/manager/service.go, tests/e2e/json_rpc_test.go
Add alias parsing for `eea_sendTransaction`
- #148
=> Alias eea send transaction

.env.dev.sample, Makefile, cmd/flags/sync.go, cmd/sync.go, docker-compose.dev.yml, scripts/generate-pki.sh
- Rename `import` command by `sync`
- Fix installation of cfssl go dependencies for dev environments
#407
=> Rename sync command | fix cfssl issue

.env.dev.sample, Makefile, go.mod, src/auth/api/http/auth.go, src/auth/api/http/no_auth.go, src/auth/app/service.go, tests/e2e/auth_test.go, tests/e2e/json_rpc_test.go
=> fix panic when not auth are defined

.github/workflows/update-openapi-doc.yaml
=> Fix github actions

.circleci/config.yml
=> add debug image releases

.circleci/config.yml, Dockerfile
=> #763 support for multi arch images

.circleci/config.yml, Makefile, README.md, scripts/coverage.sh, src/stores/connectors/stores/get_eth_test.go
=> added codecov to CI/CD

.circleci/config.yml, Dockerfile
=> 763 sign docker image

.circleci/config.yml, .codecov.yml, Makefile, README.md, scripts/coverage.sh
=> 362 code coverage v2

.circleci/config.yml
=> fix typo in circleci

Makefile, codecov.yml, scripts/coverage.sh, tests/acceptance/aliases.go
=> Improving codecov settings

pkg/jsonrpc/client_http_test.go, pkg/jsonrpc/errors.go, tests/e2e/environment.go, tests/e2e/json_rpc_test.go
=> improve e2e verbosing

tests/e2e/json_rpc_test.go
=> make e2e idempotent in case of error

.circleci/config.yml, Makefile, pkg/websocket/proxy.go
=> add race tests and fix caught issue

cmd/migrate.go, cmd/run.go, cmd/sync.go
=> silence usage message if err

CHANGELOG.md, cmd/flags/postgres.go, cmd/migrate.go, deps/docker-compose.yml, docker-compose.dev.yml, docker-compose.yml
=> support no url encoded db passwords

CHANGELOG.md, cmd/flags/oidc.go, go.mod, go.sum, sonar-project.properties, src/infra/aws/client/client.go, src/infra/aws/client/kms.go, src/infra/aws/client/parsers.go, src/stores/store/keys/aws/aws.go, src/stores/store/keys/aws/aws_test.go, src/vaults/service/vaults/create_aws.go, src/vaults/service/vaults/create_aws_test.go, src/vaults/service/vaults/create_hashicorp_test.go, src/vaults/service/vaults/get_test.go, tests/e2e/auth_test.go, tests/e2e/json_rpc_test.go, tests/e2e/keys_test.go, tests/e2e/secrets_test.go
=> 485 aws retry

.circleci/config.yml
=> small e2e run optimizations

.github/dependabot.yml
=> add dependency bot workflow

CHANGELOG.md, pkg/crypto/ecdsa.go, pkg/crypto/ecdsa/secp256k1.go, pkg/crypto/eddsa.go, pkg/crypto/eddsa/babyjubjub.go, pkg/crypto/eddsa/ed25519.go, pkg/crypto/eddsa/x25519.go, src/entities/algo.go, src/stores/connectors/keys/create_test.go, src/stores/connectors/keys/keys.go, src/stores/store/keys/hashicorp/hashicorp.go, src/stores/store/keys/hashicorp/hashicorp_test.go, src/stores/store/keys/local/local.go, src/stores/store/keys/local/local_test.go, src/utils/service/utils/keys_verify.go, src/utils/service/utils/keys_verify_test.go
=> implement support for ed25519

CHANGELOG.md, src/nodes/interceptor/eea_send_transaction.go, tests/e2e/json_rpc_test.go
=> fixed eea gas calculation when To is nil

Makefile, src/stores/connectors/ethereum/sign.go, src/stores/connectors/ethereum/sign_test.go
Max retries to 20 for AKV malleability
=> Max retries to 20 for AKV malleability

.circleci/config.yml, src/stores/api/types/testutils/faker.go
- Align both Staging and QA deployments
#522
=> Align Staging and QA deployments

src/auth/service/authenticator/authenticator.go
=> solve panic issue on high demand

LICENSE, README.md
=> chore(LICENSE): change LICENSE to Apache-2.0
